### PR TITLE
WIP: Refactor Issuer to be stateless and behave nicely on misconfiguration

### LINKED ISSUE #3: Add more status conditions to surface misconfiguration to the users
It would be better to have more status conditions on the (Cluster)Issuer. so that you could tell whether an Issuer is ready to issue certificates, and if not, why. For example, insufficient permissions or incorrect credentials

The issuer spec/status should contain enough information for the CertificateRequest controller to create a CAS client on the fly, rather than configuring a long-lived client at the reconcile step and storing it in a `sync.Map` as it is now.

### LINKED ISSUE #6: Error with missing secret
A missing credential secret triggers an ERROR - together with stack trace.

```
2020-11-11T18:44:56.842Z        ERROR   controller      Reconciler error        {"reconcilerGroup": "cas-issuer.jetstack.io", "reconcilerKind": "GoogleCASClusterIssuer", "controller": "googlecasclusterissuer", "name": "bates-cas", "namespace": "", "error": "Secret \"googlesa\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:90
```

### PR DESCRIPTION
**Pull request by jakexks**
Fixes #3 
Fixes #6

### CODE REVIEW

**Comment by maelvls** [comment]
I tried to create a CAS on my gcp project (jetstack-mael-valais) but coulnd't find a way to create it with `gcloud`; I guess that's because it is not GA yet? Do I have to use the gcp console UI?

File: pkg/cas/cas.go [hunk 1]
```diff
@@ -18,32 +18,121 @@ limitations under the License.
...
+type Signer interface {
+	// Sign signs a CSR and returns a cert and chain
+	Sign([]byte, time.Duration) ([]byte, []byte, error)
 }
 
-// casClient is a Client that talks to the Google Private CA API
-type casClient struct {
-	client *privateca.CertificateAuthorityClient
+// A SignerBuilder constructs a Signer from an Issuer Spec
+type SignerBuilder func(ctx context.Context, spec *v1alpha1.GoogleCASIssuerSpec, client client.Client) (Signer, error)
```
Comment (maelvls) [inline pkg/cas/cas.go:46]: Is it being used? I could not find where it is being used 😓

**Review by maelvls — COMMENTED** [review]
It would probably be worth adding some events + a failing condition to let the user know that their CR has failed 👍
